# Generated by Django 3.2.10 on 2021-12-22 23:50

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='tournament',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament'),
        ),
    ]
