# Generated by Django 3.2.10 on 2021-12-23 00:13

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='tournaments.round'),
        ),
    ]
