# Generated by Django 3.2.10 on 2021-12-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_alter_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='opponent_color',
            field=models.CharField(default='#E2DFB6', max_length=7),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_color',
            field=models.CharField(default='#ADD0E4', max_length=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent_dummy',
            field=models.BooleanField(default=False, verbose_name='dummy'),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent_score',
            field=models.PositiveIntegerField(default=0, verbose_name='pts'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_dummy',
            field=models.BooleanField(default=False, verbose_name='dummy'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_score',
            field=models.PositiveIntegerField(default=0, verbose_name='pts'),
        ),
    ]
