# Generated by Django 3.2.10 on 2021-12-26 21:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_auto_20211223_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliminationRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tournament', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='elimination_rounds', to='tournaments.tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EliminationGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField()),
                ('player_score_0', models.PositiveIntegerField(default=0)),
                ('opponent_score_0', models.PositiveIntegerField(default=0)),
                ('player_score_1', models.PositiveIntegerField(default=0)),
                ('opponent_score_1', models.PositiveIntegerField(default=0)),
                ('player_score_2', models.PositiveIntegerField(default=0)),
                ('opponent_score_2', models.PositiveIntegerField(default=0)),
                ('games_finished', models.PositiveIntegerField(default=0)),
                ('elimination_round', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournaments.eliminationround')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='tournaments.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='tournaments.player')),
            ],
        ),
    ]
