# Generated by Django 3.2.10 on 2021-12-26 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_eliminationgame_eliminationround'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eliminationround',
            options={'ordering': ['-round_date']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-round_date']},
        ),
        migrations.RemoveField(
            model_name='eliminationgame',
            name='game_date',
        ),
        migrations.AddField(
            model_name='eliminationround',
            name='round_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
