# Generated by Django 3.2.10 on 2021-12-26 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_remove_eliminationgame_games_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='first_place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place', to='tournaments.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place', to='tournaments.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='third_place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place', to='tournaments.player'),
        ),
    ]
