# Generated by Django 3.2.10 on 2022-04-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_auto_20211226_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='first_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place', to='tournaments.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='second_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place', to='tournaments.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='third_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place', to='tournaments.player'),
        ),
    ]
