# Generated by Django 3.2.10 on 2021-12-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eurobot_pages', '0002_tournamentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='richtextpage',
            name='raw_html',
            field=models.BooleanField(default=False),
        ),
    ]
