# Generated by Django 3.2.10 on 2021-12-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eurobot_pages', '0003_richtextpage_raw_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richtextpage',
            name='raw_html',
        ),
    ]
