# Generated by Django 3.2.10 on 2022-01-10 22:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eurobot_pages', '0006_tournamentstandings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('richtextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eurobot_pages.richtextpage')),
                ('summary', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('eurobot_pages.richtextpage',),
        ),
        migrations.CreateModel(
            name='BlogListing',
            fields=[
                ('richtextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eurobot_pages.richtextpage')),
                ('custom_title', models.CharField(help_text='Overwrites the default title', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('eurobot_pages.richtextpage',),
        ),
    ]
