# Generated by Django 3.2.10 on 2022-01-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eurobot_pages', '0007_blogentry_bloglisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglisting',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Overwrites the default title', max_length=100, null=True),
        ),
    ]
