# Generated by Django 3.2.10 on 2022-01-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eurobot_pages', '0012_alter_richtextpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richtextpage',
            name='body',
        ),
    ]
