# Generated by Django 3.2.10 on 2022-01-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_auto_20211226_2304'),
        ('eurobot_pages', '0013_remove_richtextpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentinfo',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentrounds',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentstandings',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament'),
        ),
    ]
