# Generated by Django 3.2.10 on 2022-04-26 21:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eurobot_pages', '0015_auto_20220113_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='richtextpage',
            name='footer_content',
            field=wagtail.core.fields.StreamField([('full_richtext', wagtail.core.blocks.RichTextBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
